export const SAGA_INITIAL_USER = 'SAGA_INITIAL_USER'
export const SAGA_REGISTER_USER = 'SAGA_REGISTER_USER'
export const SAGA_LOGIN_USER = 'SAGA_LOGIN_USER'
export const SAGA_CHECK_AUTH = 'SAGA_CHECK_AUTH'