export const USER_INITIAL = 'USER_INITIAL'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGIN = 'USER_LOGIN'

export const USER_SET_STATUS_REGISTER = 'USER_SET_STATUS_REGISTER'
export const USER_SET_STATUS_LOGIN = 'USER_SET_STATUS_LOGIN'